const aboutModalScenario = require('./about-modal'),
      accordionsScenario = require('./accordions'),
      alertsScenario = require('./alerts'),
      applicationLauncherScenario = require('./application-launcher'),
      badgesScenario = require('./badges'),
      blankSlateScenario = require('./blank-slate'),
      bootstrapComboboxScenario = require('./bootstrap-combobox'),
      bootstrapDatepickerScenario = require('./bootstrap-datepicker'),
      bootstrapSelectScenario = require('./bootstrap-select'),
      bootstrapSwitchScenario = require('./bootstrap-switch'),
      bootstrapTouchspinScenario = require('./bootstrap-touchspin'),
      bootstrapTreeviewScenario = require('./bootstrap-treeview'),
      breadcrumbsScenario = require('./breadcrumbs'),
      buttonsScenario = require('./buttons'),
      cardViewCardVariatonsScenario = require('./card-view-card-variatons'),
      codeScenario = require('./code'),
      dropdownsScenario = require('./dropdowns'),
      formsScenario = require('./forms'),
      iconsScenario = require('./icons'),
      infoTipScenario = require('./info-tip'),
      labelsScenario = require('./labels'),
      listGroupScenario = require('./list-group'),
      listScenario = require('./list'),
      listViewRowsScenario = require('./list-view-rows'),
      modalsScenario = require('./modals'),
      navbarScenario = require('./navbar'),
      paginationScenario = require('./pagination'),
      panelsScenario = require('./panels'),
      popoversScenario = require('./popovers'),
      progressBarsScenario = require('./progress-bars'),
      searchScenario = require('./search'),
      spinnerScenario = require('./spinner'),
      tableViewColumnsScenario = require('./table-view-columns'),
      tableViewNavbarScenario = require('./table-view-navbar'),
      tableViewScenario = require('./table-view'),
      tablesScenario = require('./tables'),
      tabsScenario = require('./tabs'),
      timePickerScenario = require('./time-picker'),
      toastsScenario = require('./toasts'),
      toolbarScenario = require('./toolbar'),
      tooltipScenario = require('./tooltip'),
      typographyScenario = require('./typography'),
      wizardScenario = require('./wizard'),
      areaChartsScenario = require('./area-charts'),
      barChartsScenario = require('./bar-charts'),
      donutChartsScenario = require('./donut-charts'),
      lineChartsScenario = require('./line-charts'),
      pieChartsScenario = require('./pie-charts'),
      utilizationBarChartsScenario = require('./utilization-bar-charts'),
      basicScenario = require('./basic'),
      treeViewScenario = require('./tree-view'),
      cardViewMultiSelectScenario = require('./card-view-multi-select'),
      cardViewSingleSelectScenario = require('./card-view-single-select'),
      cardsScenario = require('./cards'),
      dashboardScenario = require('./dashboard'),
      formScenario = require('./form'),
      listViewCompoundExpansionScenario = require('./list-view-compound-expansion'),
      listViewSimpleExpansionScenario = require('./list-view-simple-expansion'),
      listViewScenario = require('./list-view'),
      loginScenario = require('./login'),
      notificationDrawerHoriztonalNavScenario = require('./notification-drawer-horiztonal-nav'),
      notificationDrawerVerticalNavScenario = require('./notification-drawer-vertical-nav'),
      paginationCardViewScenario = require('./pagination-card-view'),
      paginationListViewScenario = require('./pagination-list-view'),
      paginationTableViewScenario = require('./pagination-table-view'),
      tabScenario = require('./tab'),
      typography2Scenario = require('./typography2');

const scenarios = [
  ...aboutModalScenario,
  ...accordionsScenario,
  ...alertsScenario,
  ...applicationLauncherScenario,
  ...badgesScenario,
  ...blankSlateScenario,
  ...bootstrapComboboxScenario,
  ...bootstrapDatepickerScenario,
  ...bootstrapSelectScenario,
  ...bootstrapSwitchScenario,
  ...bootstrapTouchspinScenario,
  ...bootstrapTreeviewScenario,
  ...breadcrumbsScenario,
  ...buttonsScenario,
  ...cardViewCardVariatonsScenario,
  ...codeScenario,
  ...dropdownsScenario,
  ...formsScenario,
  ...iconsScenario,
  ...infoTipScenario,
  ...labelsScenario,
  ...listGroupScenario,
  ...listScenario,
  ...listViewRowsScenario,
  ...modalsScenario,
  ...navbarScenario,
  ...paginationScenario,
  ...panelsScenario,
  ...popoversScenario,
  ...progressBarsScenario,
  ...searchScenario,
  ...spinnerScenario,
  ...tableViewColumnsScenario,
  ...tableViewNavbarScenario,
  ...tableViewScenario,
  ...tablesScenario,
  ...tabsScenario,
  ...timePickerScenario,
  ...toastsScenario,
  ...toolbarScenario,
  ...tooltipScenario,
  ...typographyScenario,
  ...wizardScenario,
  ...areaChartsScenario,
  ...barChartsScenario,
  ...donutChartsScenario,
  ...lineChartsScenario,
  ...pieChartsScenario,
  ...utilizationBarChartsScenario,
  ...basicScenario,
  ...treeViewScenario,
  ...cardViewMultiSelectScenario,
  ...cardViewSingleSelectScenario,
  ...cardsScenario,
  ...dashboardScenario,
  ...formScenario,
  ...listViewCompoundExpansionScenario,
  ...listViewSimpleExpansionScenario,
  ...listViewScenario,
  ...loginScenario,
  ...notificationDrawerHoriztonalNavScenario,
  ...notificationDrawerVerticalNavScenario,
  ...paginationCardViewScenario,
  ...paginationListViewScenario,
  ...paginationTableViewScenario,
  ...tabScenario
];

module.exports = scenarios
